version: '3.8'

services:

  # SERVICIO 1: La Base de Datos MySQL (La de Docker, no la de tu Windows)
  mysql-db:
    image: mysql:8.0
    container_name: elegant_cut_mysql
    restart: always
    environment:
      # 1. ESTO ES LA MAGIA: Le da permiso a Docker de crear el MySQL sin contraseña
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      # 2. El nombre de tu base de datos
      MYSQL_DATABASE: elegant_cut_db
      # OJO: Ya no ponemos MYSQL_ROOT_PASSWORD ni MYSQL_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # SERVICIO 2: Tu Backend (NestJS)
  api:
    build: .
    container_name: elegant_cut_api
    restart: always
    ports:
      - "3001:3001"
    environment:
      # MIRA AQUÍ: Fíjate que dice "root:@" (No hay nada entre los dos puntos y el arroba, porque no hay clave)
      - DATABASE_URL=mysql://root:@mysql-db:3306/elegant_cut_db
      - PORT=3001
    depends_on:
      - mysql-db

# VOLUMEN: El "disco duro" para guardar tus datos
volumes:
  mysql_data:
